### ISSUE TITLE
#US2 Cuenta

### ISSUE THREAD

**Issue by verodam** [profeale/PBKispcgrupoBx2#2]
Como usuario, quiero disponer de una cuenta propia (posibilidad de registro) para realizar funciones personalizadas del sitio web.
Como usuario quiero acceder a una pagina de bienvenida y poder disponer de información de que trata dicha el sitio. 

- [x] #34
- [ ] #33
- [ ] #35

**Comment by Ferchy341** [comment]
------- Tareas Realizada ------
